name: Detect Deploy Flag
description: Detects the deploy flag based on the event and branch

outputs:
  flag:
    description: The deploy flag
    value: ${{ steps.flag.outputs.flag }}

runs:
  using: composite
  steps:
    - name: Detect deploy flag
      id: flag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "flag=--preview" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "flag=--prod" >> $GITHUB_OUTPUT
        else
          echo "flag=--next" >> $GITHUB_OUTPUT
        fi
      shell: bash
