/*
 * Builds dist/styles.css and its declaration file.
 *
 * Radix Themes ships a fully flattened stylesheet (no @import rules), so we
 * inline it rather than re-exporting it with `@import '@radix-ui/themes/...'`.
 * A bare specifier inside CSS is not portable: Parcel resolves CSS imports
 * relative to the importing file and never falls back to node_modules — it
 * requires its own `npm:` scheme — so a published stylesheet whose first line
 * is a bare @import cannot be bundled by a Parcel app at all, and there is
 * nothing that app can do about it short of patching node_modules. Inlining
 * makes the file work anywhere unchanged.
 *
 * Which Radix version gets baked in is pinned exactly in package.json, since
 * inlining takes a copy: without the pin a later rebuild could quietly ship
 * different CSS than the one this package was tested against.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

const radixRoot = dirname(require.resolve('@radix-ui/themes/package.json'));
const radixVersion = JSON.parse(
  readFileSync(join(radixRoot, 'package.json'), 'utf8'),
).version;

/*
 * Colocated component styles are collected here rather than imported from the
 * component, which would leave a bare CSS specifier in the published bundle.
 * Sorted so the cascade does not depend on directory order.
 */
const sourceDirectory = join(packageRoot, 'src');
const componentStyles = readdirSync(sourceDirectory, {
  recursive: true,
  encoding: 'utf8',
})
  .filter((entry) => entry.endsWith('.styles.css'))
  .sort()
  .flatMap((entry) => [
    `/* ${entry.replaceAll('\\', '/')} */`,
    readFileSync(join(sourceDirectory, entry), 'utf8'),
  ]);

const output = [
  `/* @radix-ui/themes@${radixVersion} — inlined at build time */`,
  readFileSync(join(radixRoot, 'styles.css'), 'utf8'),
  '/* @rango-dev/whale — design system styles */',
  readFileSync(join(sourceDirectory, 'styles.css'), 'utf8'),
  ...componentStyles,
].join('\n');

const outputDirectory = join(packageRoot, 'dist');
mkdirSync(outputDirectory, { recursive: true });
writeFileSync(join(outputDirectory, 'styles.css'), output, 'utf8');

/*
 * TypeScript will not accept `import '@rango-dev/whale/styles.css'` unless it
 * finds a declaration for it. It looks for one by appending extensions to the
 * resolved path, so a file named exactly `styles.css.d.ts` next to the
 * stylesheet is what it wants — see the `exports` and `typesVersions` entries
 * in package.json, which point both resolution modes at it. The module is
 * empty because the import is for side effects only.
 */
const declaration = [
  '// Generated by scripts/build-styles.mjs — declares the side-effect-only',
  '// stylesheet import so it type-checks in consumers.',
  'export {};',
  '',
].join('\n');
writeFileSync(join(outputDirectory, 'styles.css.d.ts'), declaration, 'utf8');

const kilobytes = Math.round(Buffer.byteLength(output) / 1024);
console.log(`CSS  dist/styles.css  ${kilobytes} KB (radix ${radixVersion})`);
console.log('DTS  dist/styles.css.d.ts');
