import path from 'path';
import { getRootPath } from '../common/utils.mjs';
import type { PlatformConfig } from 'style-dictionary/types';

export const WHALE_PREFIX = 'w-';
export const OUTPUT_DIRECTORY = path.join(
  getRootPath(),
  'packages/foundation/dist',
);

const root = getRootPath();
export const TOKENS_DIRECTORY = path.join(root, 'packages/foundation/tokens');

export const DEFAULT_CSS_PLATFORM: PlatformConfig = {
  css: {
    transformGroup: 'css',
    prefix: WHALE_PREFIX,
    files: [
      {
        destination: '',
        format: 'css/variables',
        options: {
          showFileHeader: false,
        },
      },
    ],
  },
} as const;

export const DEFAULT_STYLE_DICTIONARY_CONFIG = {
  log: {
    warnings: 'disabled',
    verbosity: 'silent',
    errors: {
      brokenReferences: 'throw',
    },
  },
} as const;

export const CSS_GENERATED_HEADER = `/**
 * ⚠️ This file is auto-generated by script.
 * Do not edit this file directly.
 * Changes will be overwritten on the next build.
 */
`;
